app/views/bizapp_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from ..models import BizApp


bizapp_view = Blueprint('bizapp_view', __name__, template_folder='templates')


@bizapp_view.route('/bizapp/index')
@login_required
def index():
    try:
        return render_template('sys/bizapplist.html')
    except TemplateNotFound:
        abort(404)


@bizapp_view.route('/host/getbizapplist')
@login_required
def get_bizapp_list():
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1
    pagination = BizApp.BizApp.query.paginate(page, per_page=limit, error_out=False)
    items = pagination.items
    vos = []
    for item in items:
        vo = {"app_id": item.app_id, "app_name": item.app_name, "owner_phone": item.owner_phone, "owner_id": item.owner_id, "internal_ips": item.internal_ips}
        vos.append(vo)

    return jsonify({"total": pagination.total, "rows": vos})


@bizapp_view.route("/bizapp/searchmyapplistpage")
@login_required
def search_my_app_list_page():
    current_user_id = current_user.userid
    page = request.values.get('page')
    term = request.values.get('search', default="")
    limit = 10
    if term != "":
        pagination = BizApp.BizApp.query.filter(BizApp.BizApp.dev_id == current_user_id, BizApp.BizApp.app_id.like(term + '%')).paginate(page, per_page=limit, error_out=False)
    else:
        pagination = BizApp.BizApp.query.filter(BizApp.BizApp.dev_id == current_user_id).paginate(page, per_page=limit, error_out=False)

    items = pagination.items

    vos = []
    for item in items:
        vo = {"id": item.app_id, "text": item.app_id}
        vos.append(vo)

    return jsonify({"total": pagination.total, "results": vos})

app/views/wf_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from ..models import Deploy, BizApp, WfTask, WfTaskHist
from .. import db
from ..utils import data_dicts
from app.service import wf_service
from ..tasks import web_app_task


wf_view = Blueprint('wf_view', __name__, template_folder='templates')


@wf_view.route('/wf/todotasklist')
@login_required
def todo_task_list():
    try:
        return render_template('wf/todotasklist.html')
    except TemplateNotFound:
        abort(404)


@wf_view.route('/wf/gettodotasklist')
@login_required
def get_todo_task_list():
    current_user_id = current_user.userid
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1

    dtos = []
    task_proxy_result = db.session.execute("""SELECT A.*, B.app_id, B.app_version, B.env_id 
    FROM wf_task A JOIN biz_deploy B ON A.deploy_id = B.deploy_id 
    WHERE A.assignee_id = :assignee_id LIMIT :start, :limit""",
                                           {'assignee_id': current_user_id, 'start': offset, 'limit': limit})

    for rp in task_proxy_result:
        app_id = rp.app_id
        vo = {"app_id": app_id, "app_version": rp.app_version, "env_id": rp.env_id,
              "created_at": rp.created_at.strftime('%Y-%m-%d %H:%M:%S'), "act_name": rp.act_name,
              "act_type": rp.act_type, "task_id": rp.task_id }
        dtos.append(vo)

    task_proxy_result.close()

    count_proxy_result = db.session.execute("SELECT COUNT(*) as total FROM wf_task WHERE assignee_id=:assignee_id",
                                            {'assignee_id': current_user_id})
    count_proxy_result_fetchone = count_proxy_result.fetchone()
    count_proxy_result.close()
    db.session.close()
    total = count_proxy_result_fetchone.total

    return jsonify({"total": total, "rows": dtos})

    # pagination = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_result == 0).paginate(page, per_page=limit, error_out=False)
    # items = pagination.items
    # vos = []
    # for item in items:
    #    vo = {"app_id": item.app_id, "app_version": item.app_version, "env_id": item.env_id,
    #         "deploy_result": item.deploy_result, "created_at": item.created_at.strftime('%Y-%m-%d %H:%M:%S'), "created_by": item.creator_account}
    #    vos.append(vo)

    # return jsonify({"total": pagination.total, "rows": vos})


@wf_view.route('/wf/adddeploy')
@login_required
def add_deploy():
    return render_template('wf/adddeploy.html')


@wf_view.route('/wf/adddeploysuccess', methods=['POST'])
@login_required
def add_deploy_success():
    result = {"status": 200, "message": ""}
    current_user_id = current_user.userid
    current_user_name = current_user.account
    appid = request.values.get('appid')
    envid = request.values.get('envid')
    version = None
    wf_service.create_deploy_task(appid, envid, version, current_user_id, current_user_name)
    return jsonify(result)


@wf_view.route('/wf/confirmversiontask')
@login_required
def confirm_version_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 3:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmVersion:
        abort(500)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmversiontask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmversiontasksuccess', methods=['POST'])
@login_required
def confirm_version_task_success():
    result = {"status": 200, "message": ""}
    version = request.values.get('app_version')
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')
    if version is None:
        result["status"] = 500
        result["message"] = "提交的数据不正确"

    wf_service.confirm_version_task(task_id, deploy_id, app_id, version)
    return jsonify(result)


@wf_view.route('/wf/confirmpublishtask')
@login_required
def confirm_publish_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 2:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmPublish:
        abort(500)

    if task_model.assignee_id != current_user.userid:
        abort(403)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmpublishtask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmpublishtasksuccess', methods=['POST'])
@login_required
def confirm_publish_task_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    wf_service.confirm_publish_task(task_id, deploy_id, app_id)

    bizapp = BizApp.BizApp.query.filter(BizApp.BizApp.app_id == app_id).first()
    # 调用celery开始发布
    # web_app_task.deploy_app_task_async.delay(deploy_id=deploy_id, bizapp=bizapp)
    web_app_task.deploy_app_task_async(deploy_id, bizapp)
    return jsonify(result)


@wf_view.route('/wf/testdeploy')
@login_required
def test_deploy():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('/wf/testdeploy.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/testdeploysuccess')
@login_required
def test_deploy_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    return jsonify(result)

app/templates/wf/adddeploy.html
{% extends '_layout_win.html' %}
{% block title %}用户管理{% endblock %}
{% block main %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <div class="container">
    <div class="row">

<form class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 col-md-2 col-sm-2 control-label">应用名称</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
      <select class="appid_data form-control" name="appid"></select>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">环境</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
      <select class="form-control" name="envid">
          <option value="production">生产环境</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="button" class="btn btn-default">保存</button>
    </div>
  </div>
</form>
    </div>
    </div>

    <script>
        $('button').click(function () {
            if(appselect.val() == null || appselect.val() == ''){
                alert('请选择应用');return false;
            }
             if($('select[name=envid]').val() == ''){
                alert('请选择发布环境');return false;
            }

            var fmdata = {"appid":appselect.val(), "envid":$('select[name=envid]').val()}
            
            $.post("{{ url_for('wf_view.add_deploy_success') }}", fmdata, function (result) {
                if(result.status == 200) {
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index);
                    parent.refershTableList();
                }else {
                    alert(result.message)
                }
            })

            return false;
        })

        $(function () {

        })

    var appselect = $('.appid_data').select2({
      ajax: {
        url: '{{ url_for('bizapp_view.search_my_app_list_page') }}',
        dataType: 'json',
        data: function (params) {
            var query = {
                search: params.term,
                type: 'public'
            }
            // Query parameters will be ?search=[term]&type=public
            return query;
        },

        processResults: function (data, params) {
            params.page = params.page || 1;

            return {
                results: data.results,
                pagination: {
                    more: (params.page * 10) < data.count_filtered
                }
            };
        }

      }
    });
    </script>
{% endblock %}

app/templates/wf/confirmpublishtask.html
{% extends '_layout_win.html' %}
{% block title %}用户管理{% endblock %}
{% block main %}

    <div class="container">
    <div class="row">

<form class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 col-md-2 col-sm-2 control-label">应用名称</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">环境</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.env_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">版本号</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_version }}</p>
        <input type="hidden" name="task_id" value="{{ task.task_id }}">
        <input type="hidden" name="deploy_id" value="{{ deploy.deploy_id }}">
        <input type="hidden" name="app_id" value="{{ deploy.app_id }}">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="button" class="btn btn-primary">确认发布</button>
    </div>
  </div>
</form>
    </div>
    </div>

    <script type="text/javascript">
        $('button').click(function () {
            if(! confirm('确认发布吗？')){
                return false;
            }
            var fmdata = {"deploy_id": $('input[name=deploy_id]').val(), "task_id": $('input[name=task_id]').val(), "app_id": $('input[name=app_id]').val()}
            
            $.post("{{ url_for('wf_view.confirm_publish_task_success') }}", fmdata, function (result) {
                if(result.status == 200) {
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index);
                    parent.refreshTable();
                }else {
                    alert(result.message)
                }
            })

            return false;
        })

        $(function () {

        })

    </script>
{% endblock %}

app/templates/wf/confirmversiontask.html
{% extends '_layout_win.html' %}
{% block title %}用户管理{% endblock %}
{% block main %}

    <div class="container">
    <div class="row">

<form class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 col-md-2 col-sm-2 control-label">应用名称</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">环境</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.env_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">版本号</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <input type="text" class="form-control" name="app_version">
        <input type="hidden" name="deploy_id" value="{{ deploy.deploy_id }}">
        <input type="hidden" name="task_id" value="{{ task.task_id }}">
        <input type="hidden" name="app_id" value="{{ deploy.app_id }}">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="button" class="btn btn-default">保存</button>
    </div>
  </div>
</form>
    </div>
    </div>

    <script type="text/javascript">
        $('button').click(function () {
            if($('input[name=app_version]').val() == ''){
                alert('请填写版本号');return false;
            }
            if(! confirm('一旦进入发布流程，版本号不能修改。请确信版本号正确！')){
                return false;
            }
            var fmdata = {
                'deploy_id': $('input[name=deploy_id]').val(),
                'app_version': $('input[name=app_version]').val(),
                'task_id': $('input[name=task_id]').val(),
                'app_id': $('input[name=app_id]').val()
            }
            
            $.post("{{ url_for('wf_view.confirm_version_task_success') }}", fmdata, function (result) {
                if(result.status == 200) {
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index);
                    parent.refreshTable();
                }else {
                    alert(result.message)
                }
            })

            return false;
        })

        $(function () {

        })

    </script>
{% endblock %}

app/templates/wf/testdeploy.html
{% extends '_layout_win.html' %}
{% block title %}测试验证{% endblock %}
{% block main %}

    <div class="container">
    <div class="row">

<form class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 col-md-2 col-sm-2 control-label">应用名称</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">环境</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.env_id }}</p>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-lg-2 col-md-2 col-sm-2 control-label">版本号</label>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_version }}</p>
        <input type="hidden" name="task_id" value="{{ task.task_id }}">
        <input type="hidden" name="deploy_id" value="{{ deploy.deploy_id }}">
        <input type="hidden" name="app_id" value="{{ deploy.app_id }}">
    </div>
  </div>
  <div class="form-group">
      <label class="col-md-2 col-sm-2 control-label">发布价段</label>
      <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_version }}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-md-2 col-sm-2 control-label">发布结果</label>
      <div class="col-lg-10 col-md-10 col-sm-10">
        <p class="form-control-static">{{ deploy.app_version }}</p>
      </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="button" class="btn btn-primary" id="btnApprove">测试通过</button>
      <button type="button" class="btn btn-danger" id="btnReject">测试失败</button>
    </div>
  </div>
</form>
    </div>
    </div>

    <script type="text/javascript">
        $('#btnApprove').click(function () {
            if(! confirm('确认发布吗？')){
                return false;
            }
            var fmdata = {"deploy_id": $('input[name=deploy_id]').val(), "task_id": $('input[name=task_id]').val(), "app_id": $('input[name=app_id]').val()}
            
            $.post("{{ url_for('wf_view.confirm_publish_task_success') }}", fmdata, function (result) {
                if(result.status == 200) {
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index);
                    parent.refreshTable();
                }else {
                    alert(result.message)
                }
            })

            return false;
        })
        
        $('#btnReject').click(function () {
            alert('');
        })

        $(function () {

        })

    </script>
{% endblock %}

app/templates/wf/todotasklist.html
{% extends '_layout.html' %}
{% block title %}主机管理{% endblock %}
{% block main %}
    <script type="text/javascript" src="/static/layer/layer.js"></script>
    <div class="container">
{#        <div id="toolbar">#}
{#            <div class="form-inline" role="form">#}
{#                <button id="btnAdd" type="button" class="btn btn-default">创建发布任务</button>#}
{#            </div>#}
{#        </div>#}
    <table id="tbList" class="table table-bordered">

    </table>
    </div>

<script type="text/javascript">
    $(function () {
         $('#tbList').bootstrapTable({
            url: '{{ url_for("wf_view.get_todo_task_list") }}',  // 请求数据源的路由
            dataType: "json",
            pagination: true, //前端处理分页
            singleSelect: false,//是否只能单选
            search: false, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            toolbar: '#toolbar', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pageNumber: 1, //初始化加载第10页，默认第一页
            pageSize: 10, //每页的记录行数（*）
            pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
            //strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
            showColumns: true, //显示内容列下拉框
            showRefresh: true, //显示刷新按钮
            minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
            clickToSelect: true, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
            {#        height: 500, //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
            uniqueId: "userid", //每一行的唯一标识，一般为主键列
            showToggle: false, //是否显示详细视图和列表视图的切换按钮
            cardView: false, //是否显示详细视图
            //detailView: true, //是否显示父子表，设置为 true 可以显示详细页面模式,在每行最前边显示+号
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
            columns: [{  //定义表头,这个表头必须定义,下边field后边跟的字段名字必须与后端传递的字段名字相同.如:id、name、price　跟后端的字段名id  name price是完全一样的.
                field: 'app_id',
                title: '应用',
                align: 'center',  //对齐方式，居中
{#                width: '200px'  // 可以写各种样式#}
            }, {
                field: 'app_version',
                title: '版本',
                align: 'center',
            }, {
                field: 'env_id',
                title: '环境',
                align: 'center',
            }, {
                field: 'created_at',
                title: '创建时间',
                align: 'center',
            }, {
                field: 'act_name',
                title: '任务名称',
                align: 'center'
            }, {
                field: 'act_type',
                title: '任务类型',
                align: 'center',
            },{
                 field: 'operate',
                 title: '操作',
                 formatter: operateFormatter //自定义方法，添加操作按钮
            }
            ],
             onExpandRow: function (index, row, $detail) {
                 alert(1);
             }
        });
    })

    function operateFormatter(value, row, index){
        return [
                 '<a class="btn btn-primary" href="javascript:void(0)" onclick="doTask(\''+row.task_id+'\', \''+row.act_type+'\')">处理</a>'
             ].join('');
    }
    
    $('#btnAdd').click(function () {
        layer.open({
          type: 2,
          title: '创建发布任务',
          shadeClose: false,
          shade: 0.8,
          area: ['800px', '60%'],
          content: '{{ url_for('wf_view.add_deploy') }}'
        });
    })

    function refreshTable() {
        $('#tbList').bootstrapTable('refresh');
    }

    function doTask(taskid, act_type) {
        if(act_type == 'ConfirmVersion'){
            doOpenWin('{{ url_for('wf_view.confirm_version_task') }}?taskid='+taskid)
        }else if(act_type == 'ConfirmPublish') {
            doOpenWin('{{ url_for('wf_view.confirm_publish_task') }}?taskid='+taskid);
        }
    }

    function doOpenWin(url) {
         layer.open({
          type: 2,
          title: '任务处理',
          shadeClose: false,
          shade: 0.8,
          area: ['800px', '60%'],
          content: url
        });
    }
</script>
{% endblock %}