app/models/Deploy.py
from .. import db


class Deploy(db.Model):
    __tablename__ = 'biz_deploy'
    deploy_id = db.Column("deploy_id", db.Integer, primary_key=True, autoincrement=True)
    app_id = db.Column("app_id", db.String(64), unique=False, nullable=False)
    app_version = db.Column("app_version", db.String(45), unique=False, nullable=False)
    env_id = db.Column("env_id", db.String(10), unique=False, nullable=False)
    creator_id = db.Column("creator_id", db.Integer, unique=False, nullable=False)
    creator_account = db.Column("creator_account", db.String(45), unique=False, nullable=False)
    created_at = db.Column("created_at", db.DateTime, unique=False, nullable=False)
    deploy_result = db.Column("deploy_result", db.Integer, nullable=False)
    deploy_result_info = db.Column("deploy_result_info", db.String(64), nullable=False)
    wf_status = db.Column("wf_status", db.String(32), nullable=False)

    def __init__(self, app_id, app_version, env_id,
                 creator_id, creator_account, created_at, deploy_result, deploy_result_info, wf_status):
        self.app_id = app_id
        self.app_version = app_version
        self.env_id = env_id
        self.creator_id = creator_id
        self.creator_account = creator_account
        self.created_at = created_at
        self.deploy_result = deploy_result
        self.deploy_result_info = deploy_result_info
        self.wf_status = wf_status

app/views/deploy_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from ..models import Deploy
from .. import db
from ..utils import data_dicts


deploy_view = Blueprint('deploy_view', __name__, template_folder='templates')


@deploy_view.route('/deploy/querydeploy')
def query_deploy():
    try:
        return render_template('deploy/querydeploy.html')
    except TemplateNotFound:
        abort(404)


@deploy_view.route('/deploy/doquerydeploy')
def do_query_deploy():
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    # page = offset / limit + 1
    appname = request.values.get('appname')
    sql_select = "SELECT * FROM biz_deploy WHERE wf_status = '"+data_dicts.WfActivityConst.complete+"'"
    sql_count = "SELECT COUNT(*) as total FROM biz_deploy WHERE wf_status = '"+data_dicts.WfActivityConst.complete+"'"
    if appname is not None and appname != '':
        sql_select += " AND app_id LIKE :appname"
        sql_count += " AND app_id LIKE :appname"

        sql_select += " ORDER BY deploy_id DESC LIMIT :start, :limit "

    params = {'start': offset, 'limit': limit, 'appname': '%'+appname+'%'}
    task_proxy_result = db.session.execute(sql_select, {'start': offset, 'limit': limit, 'appname': '%'+appname+'%'})
    dtos = []
    for rp in task_proxy_result:
        vo = {"app_id": rp.app_id, "app_version": rp.app_version, "env_id": rp.env_id,
              "deploy_result":data_dicts.DeployResultEnum.convert_to_desc(rp.deploy_result),
              "created_at": rp.created_at.strftime('%Y-%m-%d %H:%M:%S'),
              "created_by": rp.creator_account, "wf_status": rp.wf_status}
        dtos.append(vo)

    task_proxy_result.close()

    count_proxy_result = db.session.execute(sql_count, params)
    count_proxy_result_fetchone = count_proxy_result.fetchone()
    count_proxy_result.close()
    db.session.close()
    total = count_proxy_result_fetchone.total

    return jsonify({"total": total, "rows": dtos})
    # pagination = Deploy.Deploy.query.filter(Deploy.Deploy.wf_status._in(['Publishing', 'Published', 'Test']))
    # .paginate(page, per_page=limit, error_out=False)
    # items = pagination.items


@deploy_view.route('/deploy/listmyqlldeploy')
@login_required
def list_my_all_deploy():
    try:
        return render_template('deploy/listalldeploy.html')
    except TemplateNotFound:
        abort(404)


@deploy_view.route('/deploy/dolistmyalldeploy')
@login_required
def do_list_my_all_deploy():
    current_user_id = current_user.userid
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1
    pagination = Deploy.Deploy.query.filter(Deploy.Deploy.creator_id == current_user_id)\
        .paginate(page, per_page=limit, error_out=False)
    items = pagination.items
    vos = []
    for item in items:
        vo = {"app_id": item.app_id, "app_version": item.app_version, "env_id": item.env_id,
              "deploy_result": data_dicts.DeployResultEnum.convert_to_desc(item.deploy_result), "created_at": item.created_at.strftime('%Y-%m-%d %H:%M:%S'),
              "created_by": item.creator_account, "wf_status": data_dicts.WfActivityConst.convert_to_desc(item.wf_status)}
        vos.append(vo)

    return jsonify({"total": pagination.total, "rows": vos})

app/views/wf_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from ..models import Deploy, BizApp, WfTask, WfTaskHist
from .. import db
from ..utils import data_dicts
from app.service import wf_service
from ..tasks import web_app_task


wf_view = Blueprint('wf_view', __name__, template_folder='templates')


@wf_view.route('/wf/todotasklist')
@login_required
def todo_task_list():
    try:
        return render_template('wf/todotasklist.html')
    except TemplateNotFound:
        abort(404)


@wf_view.route('/wf/gettodotasklist')
@login_required
def get_todo_task_list():
    current_user_id = current_user.userid
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1

    dtos = []
    task_proxy_result = db.session.execute("""SELECT A.*, B.app_id, B.app_version, B.env_id 
    FROM wf_task A JOIN biz_deploy B ON A.deploy_id = B.deploy_id 
    WHERE A.assignee_id = :assignee_id LIMIT :start, :limit""",
                                           {'assignee_id': current_user_id, 'start': offset, 'limit': limit})

    for rp in task_proxy_result:
        app_id = rp.app_id
        vo = {"app_id": app_id, "app_version": rp.app_version, "env_id": rp.env_id,
              "created_at": rp.created_at.strftime('%Y-%m-%d %H:%M:%S'), "act_name": rp.act_name,
              "act_type": rp.act_type, "task_id": rp.task_id }
        dtos.append(vo)

    task_proxy_result.close()

    count_proxy_result = db.session.execute("SELECT COUNT(*) as total FROM wf_task WHERE assignee_id=:assignee_id",
                                            {'assignee_id': current_user_id})
    count_proxy_result_fetchone = count_proxy_result.fetchone()
    count_proxy_result.close()
    db.session.close()
    total = count_proxy_result_fetchone.total

    return jsonify({"total": total, "rows": dtos})

    # pagination = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_result == 0).paginate(page, per_page=limit, error_out=False)
    # items = pagination.items
    # vos = []
    # for item in items:
    #    vo = {"app_id": item.app_id, "app_version": item.app_version, "env_id": item.env_id,
    #         "deploy_result": item.deploy_result, "created_at": item.created_at.strftime('%Y-%m-%d %H:%M:%S'), "created_by": item.creator_account}
    #    vos.append(vo)

    # return jsonify({"total": pagination.total, "rows": vos})


@wf_view.route('/wf/adddeploy')
@login_required
def add_deploy():
    return render_template('wf/adddeploy.html')


@wf_view.route('/wf/adddeploysuccess', methods=['POST'])
@login_required
def add_deploy_success():
    result = {"status": 200, "message": ""}
    current_user_id = current_user.userid
    current_user_name = current_user.account
    appid = request.values.get('appid')
    envid = request.values.get('envid')
    version = None
    wf_service.create_deploy_task(appid, envid, version, current_user_id, current_user_name)
    return jsonify(result)


@wf_view.route('/wf/confirmversiontask')
@login_required
def confirm_version_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 3:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmVersion:
        abort(500)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmversiontask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmversiontasksuccess', methods=['POST'])
@login_required
def confirm_version_task_success():
    result = {"status": 200, "message": ""}
    version = request.values.get('app_version')
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')
    if version is None:
        result["status"] = 500
        result["message"] = "提交的数据不正确"

    wf_service.confirm_version_task(task_id, deploy_id, app_id, version)
    return jsonify(result)


@wf_view.route('/wf/confirmpublishtask')
@login_required
def confirm_publish_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 2:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmPublish:
        abort(500)

    if task_model.assignee_id != current_user.userid:
        abort(403)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmpublishtask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmpublishtasksuccess', methods=['POST'])
@login_required
def confirm_publish_task_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    wf_service.confirm_publish_task(task_id, deploy_id, app_id)

    bizapp = BizApp.BizApp.query.filter(BizApp.BizApp.app_id == app_id).first()
    # 调用celery开始发布
    # web_app_task.deploy_app_task_async.delay(deploy_id=deploy_id, bizapp=bizapp)
    web_app_task.deploy_app_task_async(deploy_id, bizapp)
    return jsonify(result)


@wf_view.route('/wf/testdeploy')
@login_required
def test_deploy():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('/wf/testdeploy.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/testdeploysuccess')
@login_required
def test_deploy_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    return jsonify(result)

app/templates/deploy/listalldeploy.html
{% extends '_layout.html' %}
{% block title %} 我的待办{% endblock %}
{% block main %}
    <script type="text/javascript" src="/static/layer/layer.js"></script>
    <div class="container">
    {% if current_user.type == 2 %}
      <div id="toolbar">
            <div class="form-inline" role="form">
                <button id="btnAdd" type="button" class="btn btn-default">创建发布任务</button>
            </div>
        </div>
        {% endif %}
        <table id="tbList" class="table table-bordered">

        </table>
    </div>

<script type="text/javascript">
    $(function () {
         $('#tbList').bootstrapTable({
            url: '{{ url_for("deploy_view.do_list_my_all_deploy") }}',  // 请求数据源的路由
            dataType: "json",
            pagination: true, //前端处理分页
            singleSelect: false,//是否只能单选
            search: false, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            toolbar: '#toolbar', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pageNumber: 1, //初始化加载第10页，默认第一页
            pageSize: 10, //每页的记录行数（*）
            pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
            //strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
            showColumns: true, //显示内容列下拉框
            showRefresh: true, //显示刷新按钮
            minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
            clickToSelect: true, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
            {#        height: 500, //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
            uniqueId: "userid", //每一行的唯一标识，一般为主键列
            showToggle: false, //是否显示详细视图和列表视图的切换按钮
            cardView: false, //是否显示详细视图
            //detailView: true, //是否显示父子表，设置为 true 可以显示详细页面模式,在每行最前边显示+号
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
            columns: [{  //定义表头,这个表头必须定义,下边field后边跟的字段名字必须与后端传递的字段名字相同.如:id、name、price　跟后端的字段名id  name price是完全一样的.
                field: 'app_id',
                title: '应用',
                align: 'center',  //对齐方式，居中
{#                width: '200px'  // 可以写各种样式#}
            }, {
                field: 'app_version',
                title: '版本',
                align: 'center',

            }, {
                field: 'env_id',
                title: '环境',
                align: 'center',

            }, {
                field: 'created_at',
                title: '创建时间',
                align: 'center',

            }, {
                field: 'created_by',
                title: '创建人',
                align: 'center'
            }, {
                field: 'deploy_result',
                title: '发布结果',
                align: 'center',

            }, {
                field: 'wf_status',
                title: '阶段',
                align: 'center',

            }
            ],
             onExpandRow: function (index, row, $detail) {
                 alert(1);
             }
        });
    })


    function refershTableList() {
        $('#tbList').bootstrapTable('refresh');
    }

     $('#btnAdd').click(function () {
        layer.open({
          type: 2,
          title: '创建发布任务',
          shadeClose: false,
          shade: 0.8,
          area: ['800px', '60%'],
          content: '{{ url_for('wf_view.add_deploy') }}'
        });
    })
</script>
{% endblock %}

app/templates/deploy/myalldeploylist.html
{% extends '_layout.html' %}
{% block title %} 我的待办{% endblock %}
{% block main %}
    <script type="text/javascript" src="/static/layer/layer.js"></script>
    <div class="container">
    {% if current_user.type == 2 %}
      <div id="toolbar">
            <div class="form-inline" role="form">
                <button id="btnAdd" type="button" class="btn btn-default">创建发布任务</button>
            </div>
        </div>
        {% endif %}
        <table id="tbList" class="table table-bordered">

        </table>
    </div>

<script type="text/javascript">
    $(function () {
         $('#tbList').bootstrapTable({
            url: '{{ url_for("deploy_view.get_my_all_deploy_list") }}',  // 请求数据源的路由
            dataType: "json",
            pagination: true, //前端处理分页
            singleSelect: false,//是否只能单选
            search: false, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            toolbar: '#toolbar', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pageNumber: 1, //初始化加载第10页，默认第一页
            pageSize: 10, //每页的记录行数（*）
            pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
            //strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
            showColumns: true, //显示内容列下拉框
            showRefresh: true, //显示刷新按钮
            minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
            clickToSelect: true, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
            {#        height: 500, //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
            uniqueId: "userid", //每一行的唯一标识，一般为主键列
            showToggle: false, //是否显示详细视图和列表视图的切换按钮
            cardView: false, //是否显示详细视图
            //detailView: true, //是否显示父子表，设置为 true 可以显示详细页面模式,在每行最前边显示+号
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
            columns: [{  //定义表头,这个表头必须定义,下边field后边跟的字段名字必须与后端传递的字段名字相同.如:id、name、price　跟后端的字段名id  name price是完全一样的.
                field: 'app_id',
                title: '应用',
                align: 'center',  //对齐方式，居中
{#                width: '200px'  // 可以写各种样式#}
            }, {
                field: 'app_version',
                title: '版本',
                align: 'center',

            }, {
                field: 'env_id',
                title: '环境',
                align: 'center',

            }, {
                field: 'created_at',
                title: '创建时间',
                align: 'center',

            }, {
                field: 'created_by',
                title: '创建人',
                align: 'center'
            }, {
                field: 'deploy_result',
                title: '发布结果',
                align: 'center',

            }, {
                field: 'wf_status',
                title: '阶段',
                align: 'center',

            }
            ],
             onExpandRow: function (index, row, $detail) {
                 alert(1);
             }
        });
    })


    function refershTableList() {
        $('#tbList').bootstrapTable('refresh');
    }

     $('#btnAdd').click(function () {
        layer.open({
          type: 2,
          title: '创建发布任务',
          shadeClose: false,
          shade: 0.8,
          area: ['800px', '60%'],
          content: '{{ url_for('wf_view.add_deploy') }}'
        });
    })
</script>
{% endblock %}

app/templates/deploy/pendinglist.html
{% extends '_layout.html' %}
{% block title %}主机管理{% endblock %}
{% block main %}
    <script type="text/javascript" src="/static/layer/layer.js"></script>
    <div class="container">

        <table id="tbList" class="table table-bordered">

        </table>
    </div>

<script type="text/javascript">
    $(function () {
         $('#tbList').bootstrapTable({
            url: '{{ url_for("deploy_view.get_pending_list") }}',  // 请求数据源的路由
            dataType: "json",
            pagination: true, //前端处理分页
            singleSelect: false,//是否只能单选
            search: false, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            toolbar: '#toolbar', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pageNumber: 1, //初始化加载第10页，默认第一页
            pageSize: 10, //每页的记录行数（*）
            pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
            //strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
            showColumns: true, //显示内容列下拉框
            showRefresh: true, //显示刷新按钮
            minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
            clickToSelect: true, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
            {#        height: 500, //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
            uniqueId: "userid", //每一行的唯一标识，一般为主键列
            showToggle: false, //是否显示详细视图和列表视图的切换按钮
            cardView: false, //是否显示详细视图
            //detailView: true, //是否显示父子表，设置为 true 可以显示详细页面模式,在每行最前边显示+号
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
            columns: [{  //定义表头,这个表头必须定义,下边field后边跟的字段名字必须与后端传递的字段名字相同.如:id、name、price　跟后端的字段名id  name price是完全一样的.
                field: 'app_id',
                title: '应用',
                align: 'center',  //对齐方式，居中
{#                width: '200px'  // 可以写各种样式#}
            }, {
                field: 'app_version',
                title: '版本',
                align: 'center',

            }, {
                field: 'env_id',
                title: '环境',
                align: 'center',

            }, {
                field: 'created_at',
                title: '创建时间',
                align: 'center',

            }, {
                field: 'created_by',
                title: '创建人',
                align: 'center'
            }, {
                field: 'deploy_result',
                title: '发布结果',
                align: 'center',

            }, {
                field: 'wf_status',
                title: '阶段',
                align: 'center',

            }
            ],
             onExpandRow: function (index, row, $detail) {
                 alert(1);
             }
        });
    })


    function refershHostList() {
        $('#tbhostlist').bootstrapTable('refresh');
    }

     $('#btnAdd').click(function () {
        layer.open({
          type: 2,
          title: '创建发布任务',
          shadeClose: false,
          shade: 0.8,
          area: ['800px', '60%'],
          content: '{{ url_for('wf_view.add_deploy') }}'
        });
    })
</script>
{% endblock %}

app/templates/deploy/querydeploy.html
{% extends '_layout.html' %}
{% block title %}主机管理{% endblock %}
{% block main %}
    <script type="text/javascript" src="/static/layer/layer.js"></script>
    <div class="container">
        <div class="toolbar">
            <div class="form-inline">
                <label >应用名称：</label>
                <input type="text" class="form-control" id="txtAppName">
                <button type="button" class="btn btn-default" id="btnQuery">查询</button>
            </div>
        </div>
        <table id="tbList" class="table table-bordered" data-query-params="queryParams" data-query-params-type="limit">

        </table>
    </div>

<script type="text/javascript">
    var oTableInit;
    $(function () {
          oTableInit = $('#tbList').bootstrapTable({
            url: '{{ url_for("deploy_view.do_query_deploy") }}',  // 请求数据源的路由
            dataType: "json",
            pagination: true, //前端处理分页
            singleSelect: false,//是否只能单选
            search: false, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            toolbar: '#toolbar', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pageNumber: 1, //初始化加载第10页，默认第一页
            pageSize: 10, //每页的记录行数（*）
            pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
            //strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
            showColumns: true, //显示内容列下拉框
            showRefresh: true, //显示刷新按钮
            minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
            clickToSelect: true, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
            {#        height: 500, //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
            uniqueId: "deploy_id", //每一行的唯一标识，一般为主键列
            showToggle: false, //是否显示详细视图和列表视图的切换按钮
            cardView: false, //是否显示详细视图
            //detailView: true, //是否显示父子表，设置为 true 可以显示详细页面模式,在每行最前边显示+号
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
             //queryParams: buildQueryParams,
            columns: [{  //定义表头,这个表头必须定义,下边field后边跟的字段名字必须与后端传递的字段名字相同.如:id、name、price　跟后端的字段名id  name price是完全一样的.
                field: 'app_id',
                title: '应用',
                align: 'center',  //对齐方式，居中
{#                width: '200px'  // 可以写各种样式#}
            }, {
                field: 'app_version',
                title: '版本',
                align: 'center',

            }, {
                field: 'env_id',
                title: '环境',
                align: 'center',

            }, {
                field: 'created_at',
                title: '创建时间',
                align: 'center',

            }, {
                field: 'created_by',
                title: '创建人',
                align: 'center'
            }, {
                field: 'deploy_result',
                title: '发布结果',
                align: 'center',

            }, {
                field: 'wf_status',
                title: '流程阶段',
                align: 'center',

            }
            ],
             onExpandRow: function (index, row, $detail) {
                 alert(1);
             }
        });
    })

    function queryParams(params) {
        var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
                limit: params.limit,   //页面大小
                offset: params.offset,  //页码
                appname: $("#txtAppName").val()
            };
            return temp;
    }

    function refreshTable() {
        $('#tbList').bootstrapTable('refresh');
    }

    $('#btnQuery').click(function () {
        refreshTable();
    })
</script>
{% endblock %}