app/views/home_view.py
from flask import (Blueprint, render_template, abort, request, redirect, url_for, flash, jsonify)
from jinja2 import TemplateNotFound
from .. import login_manager
from ..models import User
from flask_login import login_user, logout_user
import hashlib
from .. import db
from ..utils import common_util, data_dicts


home_view = Blueprint('home_view', __name__)


@home_view.route("/")
def index():
    try:
        return render_template('home/index.html')
    except TemplateNotFound:
        abort(404)


@home_view.route('/getrecentdeploylist')
def get_recent_deploy_list():
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    # page = offset / limit + 1

    task_proxy_result = db.session.execute(
        "SELECT * FROM biz_deploy WHERE wf_status IN ('"
        + data_dicts.WfActivityConst.complete + "') ORDER BY deploy_id DESC LIMIT :start, :limit",
        {'start': offset, 'limit': limit})
    dtos = []
    for rp in task_proxy_result:
        vo = {"app_id": rp.app_id, "app_version": rp.app_version, "env_id": rp.env_id,
              "deploy_result": data_dicts.DeployResultEnum.convert_to_desc(rp.deploy_result),
              "created_at": rp.created_at.strftime('%Y-%m-%d %H:%M:%S'),
              "created_by": rp.creator_account, "wf_status": rp.wf_status}
        dtos.append(vo)

    task_proxy_result.close()

    return jsonify({"total": dtos.count(), "rows": dtos})


@home_view.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        account = request.values.get("account")
        pwd = request.values.get("password")
        pwd = pwd.encode()
        pwdhash = hashlib.md5(pwd)
        user = User.User.query.filter(User.User.account == account).first()
        if user is None:
            flash("用户不存在")
        elif user.passwordhash != pwdhash.hexdigest():
            flash("用户名或密码不存在")
        else:
            login_user(user)
            # return redirect(url_for('home_view.index'))
            return redirect(url_for('deploy_view.pending_list'))

    return render_template('home/login.html')


@home_view.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('home_view.index'))


@login_manager.user_loader
def load_user(userid):
    return User.User.query.filter(User.User.userid == userid).first()

app/views/host_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required
from jinja2 import TemplateNotFound
from ..models import Host


host_view = Blueprint('host_view', __name__, template_folder='templates')


@host_view.route('/host/index')
@login_required
def index():
    try:
        return render_template('sys/hostlist.html')
    except TemplateNotFound:
        abort(404)


@host_view.route('/host/gethostlist')
@login_required
def get_host_list():
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1
    pagination = Host.Host.query.paginate(page, per_page=limit, error_out=False)
    hostitems = pagination.items
    hostVos = []
    for hostitem in hostitems:
        hostvo = {"host_id": hostitem.host_id, "internal_ip": hostitem.internal_ip, "external_ip": hostitem.external_ip, "host_name": hostitem.host_name}
        hostVos.append(hostvo)

    return jsonify({"total": pagination.total, "rows": hostVos})

app/views/user_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from jinja2 import TemplateNotFound
from ..models import User, UserType
from flask_login import login_required
from .. import db, login_manager
import hashlib


user_view = Blueprint('user_view', __name__, template_folder='templates')


@user_view.route('/user/index')
@login_required
def index(page=1):
    try:
        return render_template('sys/userlist.html')
    except TemplateNotFound:
        abort(404)


@user_view.route('/user/getuserlist')
@login_required
def get_user_list():
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1
    pagination = User.User.query.paginate(page, per_page=limit, error_out=False)
    userEntities = pagination.items
    userVOs = []
    for userEntity in userEntities:
        typestr = UserType.UserType.convert_to_desc(userEntity.type)
        uservo = {"userid": userEntity.userid, "account": userEntity.account, "type": userEntity.type, "typedisplay": typestr}
        userVOs.append(uservo)

    return jsonify({"total": pagination.total, "rows": userVOs })


@user_view.route('/user/add', methods=['GET'])
@login_required
def add():
    return render_template("sys/adduser.html")


@user_view.route('/user/addsuccess', methods=['POST'])
@login_required
def add_success():
    result = {"status": 200, "message": ""}
    account = request.values.get('account')
    usertype = request.values.get('type')
    # 判断用户是否存在
    user = User.User.query.filter(User.User.account == account).first()
    if user is not None:
        result["status"] = 500
        result["message"] = "用户已存在"
        return jsonify(result)
    pwd = "12345678".encode()
    pwdhash = hashlib.md5(pwd).hexdigest()
    newuser = User.User(account=account, passwordhash=pwdhash, type=usertype)
    db.session.add(newuser)
    db.session.commit()
    db.session.close()
    return jsonify(result)


@login_manager.user_loader
def load_user(userid):
    return User.User.query.filter(User.User.userid == userid).first()

app/views/wf_view.py
from flask import Blueprint, render_template, abort, jsonify, request
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from ..models import Deploy, BizApp, WfTask, WfTaskHist
from .. import db
from ..utils import data_dicts
from app.service import wf_service
from ..tasks import web_app_task


wf_view = Blueprint('wf_view', __name__, template_folder='templates')


@wf_view.route('/wf/todotasklist')
@login_required
def todo_task_list():
    try:
        return render_template('wf/todotasklist.html')
    except TemplateNotFound:
        abort(404)


@wf_view.route('/wf/gettodotasklist')
@login_required
def get_todo_task_list():
    current_user_id = current_user.userid
    limitstr = request.values.get("limit")
    offsetstr = request.values.get("offset")
    limit = 10
    if limitstr.strip():
        limit = int(limitstr)
    offset = 0
    if offsetstr.strip():
        offset = int(offsetstr)
    page = offset / limit + 1

    dtos = []
    task_proxy_result = db.session.execute("""SELECT A.*, B.app_id, B.app_version, B.env_id 
    FROM wf_task A JOIN biz_deploy B ON A.deploy_id = B.deploy_id 
    WHERE A.assignee_id = :assignee_id LIMIT :start, :limit""",
                                           {'assignee_id': current_user_id, 'start': offset, 'limit': limit})

    for rp in task_proxy_result:
        app_id = rp.app_id
        vo = {"app_id": app_id, "app_version": rp.app_version, "env_id": rp.env_id,
              "created_at": rp.created_at.strftime('%Y-%m-%d %H:%M:%S'), "act_name": rp.act_name,
              "act_type": rp.act_type, "task_id": rp.task_id }
        dtos.append(vo)

    task_proxy_result.close()

    count_proxy_result = db.session.execute("SELECT COUNT(*) as total FROM wf_task WHERE assignee_id=:assignee_id",
                                            {'assignee_id': current_user_id})
    count_proxy_result_fetchone = count_proxy_result.fetchone()
    count_proxy_result.close()
    db.session.close()
    total = count_proxy_result_fetchone.total

    return jsonify({"total": total, "rows": dtos})

    # pagination = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_result == 0).paginate(page, per_page=limit, error_out=False)
    # items = pagination.items
    # vos = []
    # for item in items:
    #    vo = {"app_id": item.app_id, "app_version": item.app_version, "env_id": item.env_id,
    #         "deploy_result": item.deploy_result, "created_at": item.created_at.strftime('%Y-%m-%d %H:%M:%S'), "created_by": item.creator_account}
    #    vos.append(vo)

    # return jsonify({"total": pagination.total, "rows": vos})


@wf_view.route('/wf/adddeploy')
@login_required
def add_deploy():
    return render_template('wf/adddeploy.html')


@wf_view.route('/wf/adddeploysuccess', methods=['POST'])
@login_required
def add_deploy_success():
    result = {"status": 200, "message": ""}
    current_user_id = current_user.userid
    current_user_name = current_user.account
    appid = request.values.get('appid')
    envid = request.values.get('envid')
    version = None
    wf_service.create_deploy_task(appid, envid, version, current_user_id, current_user_name)
    return jsonify(result)


@wf_view.route('/wf/confirmversiontask')
@login_required
def confirm_version_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 3:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmVersion:
        abort(500)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmversiontask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmversiontasksuccess', methods=['POST'])
@login_required
def confirm_version_task_success():
    result = {"status": 200, "message": ""}
    version = request.values.get('app_version')
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')
    if version is None:
        result["status"] = 500
        result["message"] = "提交的数据不正确"

    wf_service.confirm_version_task(task_id, deploy_id, app_id, version)
    return jsonify(result)


@wf_view.route('/wf/confirmpublishtask')
@login_required
def confirm_publish_task():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    if task_model is None:
        abort(500)

    if current_user.type != 2:
        abort(403)

    if task_model.act_type != data_dicts.WfActivityConst.confirmPublish:
        abort(500)

    if task_model.assignee_id != current_user.userid:
        abort(403)

    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('wf/confirmpublishtask.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/confirmpublishtasksuccess', methods=['POST'])
@login_required
def confirm_publish_task_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    wf_service.confirm_publish_task(task_id, deploy_id, app_id)

    bizapp = BizApp.BizApp.query.filter(BizApp.BizApp.app_id == app_id).first()
    # 调用celery开始发布
    # web_app_task.deploy_app_task_async.delay(deploy_id=deploy_id, bizapp=bizapp)
    web_app_task.deploy_app_task_async(deploy_id, bizapp)
    return jsonify(result)


@wf_view.route('/wf/testdeploy')
@login_required
def test_deploy():
    taskid = request.values.get("taskid")
    task_model = WfTask.WfTask.query.filter(WfTask.WfTask.task_id == taskid).first()
    deploy_model = Deploy.Deploy.query.filter(Deploy.Deploy.deploy_id == task_model.deploy_id).first()
    return render_template('/wf/testdeploy.html', deploy=deploy_model, task=task_model)


@wf_view.route('/wf/testdeploysuccess')
@login_required
def test_deploy_success():
    result = {"status": 200, "message": ""}
    deploy_id = request.values.get('deploy_id')
    task_id = request.values.get('task_id')
    app_id = request.values.get('app_id')

    return jsonify(result)

app/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>自动化发布系统 {% block title %}{% endblock %}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/main.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('home_view.index') }}">自动化发布系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{{ url_for('deploy_view.query_deploy') }}"><i class="fa fa-tasks" aria-hidden="true"></i> 发布查询</a></li>
              {% if current_user.is_authenticated %}
                  {% if current_user.type == 2 %}
                      <li><a href="{{ url_for('wf_view.todo_task_list') }}"><i class="fa fa-tasks" aria-hidden="true"></i> 我的待办</a></li>
                      <li><a href="{{ url_for('deploy_view.list_my_all_deploy') }}"><i class="fa fa-tasks" aria-hidden="true"></i> 发布列表</a></li>
                  {% endif %}
                  {% if current_user.type == 3 %}
                      <li><a href="{{ url_for('wf_view.todo_task_list') }}"><i class="fa fa-tasks" aria-hidden="true"></i> 我的代办</a></li>
                  {% endif %}
                  {% if current_user.type == 1 %}
                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog" aria-hidden="true"></i> 系统管理<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{{ url_for('host_view.index') }}"><i class="fa fa-server" aria-hidden="true"></i> 主机管理</a></li>
                        <li><a href="{{ url_for('bizapp_view.index') }}"><i class="fa fa-internet-explorer" aria-hidden="true"></i> 应用管理</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">权限管理</li>
                        <li><a href="{{ url_for('user_view.index') }}"><i class="fa fa-user" aria-hidden="true"></i> 用户管理</a></li>
                      </ul>
                    </li>
                  {% endif %}

              {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.account }}<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">个人资料</a></li>
                <li><a href="{{ url_for('home_view.logout') }}">退出</a></li>
              </ul>
             </li>
              {% else %}
              <li>
              <a href="{{ url_for('home_view.login') }}">登录</a>
              </li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div style="margin-top:70px;">
    {% block main %}{% endblock %}
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</body>
</html>

app/templates/_layout_win.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>自动化发布系统</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/main.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>

<div style="margin-top:15px;">
 {% block main %}{% endblock %}
</div>
{#    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.css">#}
{#    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>#}
{#    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>#}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>
</body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>{{ e.code }}</h2>
    <div>{{ e.description }}</div>
    <div><a href="/">返回首页</a></div>
</body>
</html>

app/templates/noauth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>{{ e.code }}</h2>
    <div>您无权限访问！</div>
    <div><a href="/">返回首页</a></div>
</body>
</html>